# Usa la imagen base oficial de Nginx, la versión más reciente.
FROM nginx:latest

# Establece el directorio de trabajo dentro del contenedor en /var/www/html.
WORKDIR /var/www/html

# Elimina todos los archivos y directorios existentes dentro del directorio de trabajo.
# Principalmente por que los archivos antiguos se quedan y es mejor eliminarlos y actualizarlos.
RUN rm -rf *

# Copia el contenido del directorio 'www' del host al directorio de trabajo del contenedor
# estableciendo el propietario y grupo en www-data.
COPY --chown=www-data:www-data www/. ./

# Copia el archivo 'default.conf' del host al directorio de configuración de Nginx en el contenedor, reemplazando el archivo existente.
COPY default.conf /etc/nginx/conf.d/default.conf

# Expone el puerto 80 del contenedor para que sea accesible desde el exterior.
EXPOSE 80