# Dockerfile para la API de Python

# Usa una imagen base de Python 3.9 (o la versión que prefieras)
FROM python:3.9-slim-buster

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo requirements.txt al contenedor
COPY ./Python/requisitos.txt /app/requisitos.txt

# Instala las dependencias
RUN pip install --no-cache-dir -r requisitos.txt

# Comando para ejecutar la aplicación con Gunicorn (ajusta si no usas Gunicorn)
# 'app:app' significa:  'nombre_del_archivo:nombre_de_la_variable_app'
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
